name: Service Workflow

on:
  workflow_call:
  # interface to sub-workflow ---------------------------------------
    inputs:
      role:
        required: true
        type: string
      build_type:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      token:
        required: true
      token_sonar:
        required: true
      token_github:
        required: true
      token_ci:
        required: false
  # end of interface to sub-workflow --------------------------------

jobs:
  service:
    name: Service
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Echo Inputs
        run: echo "${{ inputs.role }}, ${{ inputs.build_type }}"
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
            path: ${{ github.workspace }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          check-latest: false
      - name: install gcovr 5.0  # WR TO DO: gcovr auf self-hosted runner installieren!
        run: |
            pip install gcovr==5.0 # 5.1 is not supported
